---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :enabled

platforms:
  - name: osx-10-10
    driver:
      box: jhcook/osx-yosemite-10.10
  - name: centos-6-6
    driver:
      box: chef/centos-6.6
  - name: ubuntu-trusty64
    driver:
      box: ubuntu/trusty64

suites:
  - name: default
    run_list:
      - recipe[osquery::default]
