---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :enabled

platforms:
  - name: osx-1010
    driver:
      box: jhcook/osx-yosemite-10.10
  - name: centos-67
    driver:
      box: bento/centos-6.7
  - name: centos-72
    driver:
      box: bento/centos-7.2
  - name: ubuntu-trusty64
    driver:
      box: ubuntu/trusty64
  - name: ubuntu/precise64
    driver:
      box: ubuntu/precise64

suites:
  - name: default
    run_list:
      - recipe[osquery::default]
